# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0002_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sub_task',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
