# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0003_task_sub_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='titles',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
