# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 00:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0007_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 7, 0, 39, 58, 51331, tzinfo=utc)),
        ),
    ]
